import { StyleSheet } from 'react-native';
import { theme } from '../../theme';
import { moderateScale, rf } from '../../utils/responsive';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3F4F6',
  },
  headerAnimWrapper: {
    position: 'absolute',
    top: moderateScale(0),
    left: moderateScale(0),
    right: moderateScale(0),
    zIndex: 100,
  },
  header: {
    paddingHorizontal: theme.spacing.lg,
    paddingTop: moderateScale(22),
    paddingBottom: moderateScale(22),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontSize: rf(19),
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.white,
  },
  clearText: {
    color: theme.colors.error,
    fontSize: theme.typography.sizes.sm,
    fontWeight: theme.typography.weights.bold,
  },
  scrollContent: {
    paddingBottom: moderateScale(220),
  },
  // Item List Card
  promoBanner: {
    backgroundColor: '#DCFCE7',
    marginHorizontal: theme.spacing.md,
    marginTop: theme.spacing.md,
    padding: theme.spacing.sm,
    borderRadius: moderateScale(8),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  promoText: {
    color: theme.colors.primary,
    fontSize: theme.typography.sizes.sm,
    fontWeight: theme.typography.weights.bold,
    marginLeft: moderateScale(6),
  },
  card: {
    backgroundColor: theme.colors.white,
    marginHorizontal: theme.spacing.md,
    marginTop: theme.spacing.md,
    borderRadius: moderateScale(16),
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: theme.spacing.md,
  },
  cartItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: theme.spacing.md,
    borderBottomWidth: 0.5,
    borderColor: theme.colors.border,
  },
  itemImage: {
    width: moderateScale(50),
    height: moderateScale(50),
    borderRadius: theme.borderRadius.sm,
    marginRight: theme.spacing.md,
  },
  itemDetails: {
    flex: 1,
    marginRight: theme.spacing.sm,
  },
  itemName: {
    fontSize: theme.typography.sizes.sm + 1,
    fontWeight: theme.typography.weights.semiBold,
    color: theme.colors.textPrimary,
    lineHeight: rf(18),
  },
  itemUnit: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.textSecondary,
    marginTop: moderateScale(2),
  },
  itemPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: moderateScale(4),
  },
  itemPrice: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.textPrimary,
  },
  itemOriginalPrice: {
    fontSize: theme.typography.sizes.xs,
    textDecorationLine: 'line-through',
    color: theme.colors.textSecondary,
    marginLeft: moderateScale(6),
  },
  unavailableText: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.error,
    fontWeight: theme.typography.weights.bold,
    marginTop: moderateScale(4),
  },
  // Coupons Section
  couponCard: {
    backgroundColor: theme.colors.white,
    marginHorizontal: theme.spacing.lg,
    marginTop: theme.spacing.md,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    padding: theme.spacing.md,
    ...theme.shadows.sm,
  },
  couponRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  couponInput: {
    flex: 1,
    height: moderateScale(40),
    marginRight: theme.spacing.md,
  },
  couponButton: {
    height: moderateScale(40),
    width: moderateScale(80),
  },
  couponSuccessText: {
    color: theme.colors.success,
    fontSize: theme.typography.sizes.xs,
    fontWeight: theme.typography.weights.bold,
    marginTop: theme.spacing.xs,
  },
  // Tipping Section
  tipCard: {
    backgroundColor: theme.colors.white,
    marginHorizontal: theme.spacing.md,
    marginTop: theme.spacing.md,
    borderRadius: moderateScale(16),
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: theme.spacing.md,
  },
  tipHeader: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.textPrimary,
    marginBottom: theme.spacing.sm,
  },
  tipRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  tipButton: {
    flex: 1,
    paddingVertical: theme.spacing.sm,
    borderWidth: 1.5,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.sm,
    alignItems: 'center',
    marginHorizontal: moderateScale(3),
  },
  tipButtonActive: {
    borderColor: theme.colors.primary,
    backgroundColor: theme.colors.primaryLight,
  },
  tipText: {
    fontSize: theme.typography.sizes.xs + 1,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.textSecondary,
  },
  tipTextActive: {
    color: theme.colors.primary,
  },
  // Bill Summary
  billCard: {
    backgroundColor: theme.colors.white,
    marginHorizontal: theme.spacing.md,
    marginTop: theme.spacing.md,
    marginBottom: moderateScale(12),
    borderRadius: moderateScale(16),
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: theme.spacing.md,
  },
  billTitle: {
    fontSize: theme.typography.sizes.sm + 1,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.textPrimary,
    marginBottom: theme.spacing.md,
  },
  billRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.sm,
  },
  billLabel: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.textSecondary,
  },
  billValue: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.textPrimary,
    fontWeight: theme.typography.weights.medium,
  },
  billValueFree: {
    color: theme.colors.success,
    fontWeight: theme.typography.weights.bold,
  },
  billValueDiscount: {
    color: theme.colors.accent,
    fontWeight: theme.typography.weights.bold,
  },
  billDivider: {
    height: moderateScale(1),
    backgroundColor: theme.colors.border,
    marginVertical: theme.spacing.sm,
  },
  billTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  billTotalLabel: {
    fontSize: theme.typography.sizes.md,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.textPrimary,
  },
  billTotalValue: {
    fontSize: theme.typography.sizes.lg,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.textPrimary,
  },
  // Empty State
  emptyScrollContent: {
    flexGrow: 1,
    paddingBottom: moderateScale(32),
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: theme.spacing.xxl,
    marginTop: moderateScale(50),
  },
  emptyIconWrapper: {
    width: moderateScale(96),
    height: moderateScale(96),
    borderRadius: moderateScale(48),
    backgroundColor: '#FFFFFF',
    elevation: 6,
    shadowColor: '#22C55E',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
  },
  emptyIconGradient: {
    width: '100%',
    height: '100%',
    borderRadius: moderateScale(48),
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  sparkleBadge: {
    position: 'absolute',
    top: moderateScale(-2),
    right: moderateScale(-2),
    backgroundColor: '#FFFFFF',
    width: moderateScale(26),
    height: moderateScale(26),
    borderRadius: moderateScale(13),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#F1F5F9',
    elevation: 3,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  emptyText: {
    fontSize: theme.typography.sizes.lg + 1,
    color: theme.colors.textPrimary,
    fontWeight: '800',
    marginTop: theme.spacing.lg,
    marginBottom: theme.spacing.xs,
  },
  emptySubtext: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    lineHeight: rf(18),
    paddingHorizontal: theme.spacing.md,
    marginBottom: theme.spacing.lg,
  },
  shopNowBtn: {
    marginTop: theme.spacing.xs,
    borderRadius: moderateScale(24),
    overflow: 'hidden',
    elevation: 4,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  shopNowBtnGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.xxl + 4,
    paddingVertical: theme.spacing.md - 1,
    justifyContent: 'center',
  },
  shopNowBtnText: {
    color: '#FFFFFF',
    fontSize: theme.typography.sizes.sm + 1,
    fontWeight: theme.typography.weights.bold,
  },
  // Popular Categories suggestions
  popularCategoriesContainer: {
    marginTop: theme.spacing.xl,
    paddingVertical: theme.spacing.md,
    borderTopWidth: 1,
    borderTopColor: '#F1F5F9',
    backgroundColor: theme.colors.white,
  },
  popularHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.lg,
    marginBottom: theme.spacing.md,
  },
  popularTitle: {
    fontSize: theme.typography.sizes.md,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.textPrimary,
  },
  popularScrollContent: {
    paddingLeft: theme.spacing.lg,
    paddingRight: theme.spacing.sm,
  },
  popularCatCard: {
    width: moderateScale(76),
    alignItems: 'center',
    marginRight: theme.spacing.md,
    backgroundColor: '#F8FAFC',
    borderRadius: moderateScale(12),
    padding: moderateScale(8),
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  popularCatImageContainer: {
    width: moderateScale(52),
    height: moderateScale(52),
    backgroundColor: '#FFFFFF',
    borderRadius: moderateScale(26),
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: moderateScale(6),
    overflow: 'hidden',
    borderWidth: 0.5,
    borderColor: '#F1F5F9',
  },
  popularCatImage: {
    width: '80%',
    height: '80%',
  },
  popularCatName: {
    fontSize: rf(9.5),
    fontWeight: '700',
    color: theme.colors.textPrimary,
    textAlign: 'center',
    width: '100%',
  },
  // Sticky Bottom Footer
  stickyFooter: {
    position: 'absolute',
    bottom: moderateScale(0),
    left: moderateScale(0),
    right: moderateScale(0),
    backgroundColor: theme.colors.white,
    borderTopLeftRadius: moderateScale(24),
    borderTopRightRadius: moderateScale(24),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 24,
    padding: theme.spacing.lg,
    paddingBottom: theme.spacing.lg,
  },
  addressSnippetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: theme.spacing.md,
  },
  addressSnippetText: {
    fontSize: rf(11),
    color: theme.colors.textSecondary,
    marginLeft: moderateScale(6),
    flex: 1,
  },
  checkoutActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  checkoutPriceBox: {
    marginRight: theme.spacing.md,
  },
  checkoutPriceText: {
    fontSize: theme.typography.sizes.xl,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.textPrimary,
  },
  checkoutPriceLabel: {
    fontSize: rf(10),
    color: theme.colors.textSecondary,
  },
  checkoutButton: {
    height: moderateScale(42),
    width: moderateScale(180),
    borderRadius: moderateScale(10),
  },
});
