import { StyleSheet } from 'react-native';
import { theme } from '../../theme';
import { moderateScale, rf } from '../../utils/responsive';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.white,
  },
  headerAnimWrapper: {
    position: 'absolute',
    top: moderateScale(0),
    left: moderateScale(0),
    right: moderateScale(0),
    zIndex: 100,
  },
  header: {
    paddingHorizontal: theme.spacing.lg,
    paddingTop: moderateScale(12),
    paddingBottom: moderateScale(12),
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(22, 101, 52, 0.2)',
  },
  headerTitle: {
    fontSize: rf(19),
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.white,
  },
  scrollContent: {
    paddingBottom: theme.spacing.xxl,
  },
  // User Profile Info Card
  profileCard: {
    backgroundColor: theme.colors.white,
    flexDirection: 'row',
    alignItems: 'center',
    padding: theme.spacing.lg,
    marginTop: theme.spacing.md,
    marginHorizontal: theme.spacing.lg,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    ...theme.shadows.sm,
  },
  avatarContainer: {
    width: moderateScale(60),
    height: moderateScale(60),
    borderRadius: moderateScale(30),
    backgroundColor: theme.colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.spacing.md,
  },
  avatarText: {
    color: theme.colors.white,
    fontSize: theme.typography.sizes.xl,
    fontWeight: theme.typography.weights.bold,
  },
  profileDetails: {
    flex: 1,
  },
  userName: {
    fontSize: theme.typography.sizes.md + 2,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.textPrimary,
  },
  userPhone: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.textSecondary,
    marginTop: moderateScale(2),
  },
  // Menu Item Card
  menuContainer: {
    backgroundColor: theme.colors.white,
    marginTop: theme.spacing.lg,
    marginHorizontal: theme.spacing.lg,
    borderRadius: theme.borderRadius.md,
    borderWidth: 1,
    borderColor: theme.colors.border,
    overflow: 'hidden',
    ...theme.shadows.sm,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: theme.spacing.md + 2,
    borderBottomWidth: 0.5,
    borderColor: theme.colors.border,
  },
  menuItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  menuItemText: {
    fontSize: theme.typography.sizes.sm + 1,
    fontWeight: theme.typography.weights.medium,
    color: theme.colors.textPrimary,
    marginLeft: theme.spacing.md,
  },
  // Logout Button
  logoutButton: {
    marginHorizontal: theme.spacing.lg,
    marginTop: theme.spacing.xl,
    backgroundColor: '#FEF2F2',
    borderWidth: 1.5,
    borderColor: '#FCA5A5',
    shadowOpacity: 0,
    elevation: 0,
  },
  logoutText: {
    color: theme.colors.error,
  },
  // Modal layout
  modalOverlay: {
    flex: 1,
    backgroundColor: theme.colors.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: theme.spacing.xl,
  },
  modalContainer: {
    backgroundColor: theme.colors.cardBackground,
    borderRadius: theme.borderRadius.lg,
    padding: theme.spacing.lg,
    width: '100%',
    maxHeight: '80%',
    ...theme.shadows.lg,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: theme.colors.border,
    paddingBottom: theme.spacing.sm,
    marginBottom: theme.spacing.md,
  },
  modalTitle: {
    fontSize: theme.typography.sizes.md + 1,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.textPrimary,
  },
  modalScrollContent: {
    paddingBottom: theme.spacing.md,
  },
  modalBodyText: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.textSecondary,
    lineHeight: rf(20),
    marginBottom: theme.spacing.md,
  },
  // Custom Edit Profile Styles
  editProfileBtn: {
    backgroundColor: '#E6F4EA',
    width: moderateScale(36),
    height: moderateScale(36),
    borderRadius: moderateScale(18),
    justifyContent: 'center',
    alignItems: 'center',
  },
  formLabel: {
    fontSize: rf(13),
    fontWeight: '700',
    color: theme.colors.textPrimary,
    marginBottom: moderateScale(6),
    marginTop: moderateScale(12),
  },
  formInput: {
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.sm,
    padding: moderateScale(10),
    fontSize: rf(14),
    color: theme.colors.textPrimary,
    backgroundColor: '#FAFAFA',
  },
  avatarListContainer: {
    marginTop: moderateScale(8),
    marginBottom: moderateScale(16),
  },
  avatarOption: {
    width: moderateScale(50),
    height: moderateScale(50),
    borderRadius: moderateScale(25),
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: moderateScale(10),
    borderWidth: 2,
    borderColor: 'transparent',
  },
  selectedAvatarOption: {
    borderColor: theme.colors.primary,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  avatarOptionEmoji: {
    fontSize: moderateScale(28),
  },
  modalFooter: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: moderateScale(16),
    borderTopWidth: 1,
    borderTopColor: theme.colors.border,
    paddingTop: moderateScale(12),
  },
  cancelBtn: {
    paddingVertical: moderateScale(10),
    paddingHorizontal: moderateScale(16),
    marginRight: moderateScale(12),
  },
  cancelBtnText: {
    color: theme.colors.textSecondary,
    fontWeight: '700',
    fontSize: rf(14),
  },
  saveBtn: {
    backgroundColor: theme.colors.primary,
    paddingVertical: moderateScale(10),
    paddingHorizontal: moderateScale(20),
    borderRadius: theme.borderRadius.sm,
  },
  saveBtnText: {
    color: theme.colors.white,
    fontWeight: '700',
    fontSize: rf(14),
  },
  // Interactive Avatar Custom Styles
  avatarWrapper: {
    position: 'relative',
    marginRight: theme.spacing.md,
  },
  cameraIconContainer: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    backgroundColor: theme.colors.primary,
    width: moderateScale(22),
    height: moderateScale(22),
    borderRadius: moderateScale(11),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: theme.colors.white,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 2,
    elevation: 2,
  },
  avatarContainerHovered: {
    opacity: 0.9,
  },
  hoverCameraOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    borderRadius: moderateScale(30),
    justifyContent: 'center',
    alignItems: 'center',
  },
});
