import { StyleSheet } from 'react-native';
import { theme } from '../../theme';
import { moderateScale, rf } from '../../utils/responsive';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F3F4F6', // Modern app gray background
  },
  // Animated wrapper for scroll-based fade/slide
  headerAnimWrapper: {
    position: 'absolute',
    top: moderateScale(0),
    left: moderateScale(0),
    right: moderateScale(0),
    zIndex: 100,
  },
  header: {
    paddingHorizontal: theme.spacing.lg,
    paddingTop: moderateScale(22),
    paddingBottom: moderateScale(22),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(22, 101, 52, 0.2)',
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerTitle: {
    fontSize: rf(19),
    fontWeight: '800',
    color: theme.colors.textPrimary,
    marginLeft: theme.spacing.md,
  },
  shareBtn: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  shareText: {
    color: theme.colors.success,
    fontSize: theme.typography.sizes.sm,
    fontWeight: '700',
    marginLeft: moderateScale(4),
  },
  scrollContent: {
    paddingBottom: moderateScale(220), // Ensure it clears the double-decker footer
  },
  // Order For Card
  orderForCard: {
    backgroundColor: theme.colors.white,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.sm + 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing.sm,
  },
  orderForText: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: '700',
    color: theme.colors.textPrimary,
  },
  changeText: {
    color: theme.colors.success,
    fontSize: theme.typography.sizes.sm,
    fontWeight: '700',
  },
  // Delivery Estimate Card
  deliveryEstimateCard: {
    backgroundColor: theme.colors.white,
    padding: theme.spacing.lg,
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: theme.spacing.md,
    marginTop: theme.spacing.md,
    marginBottom: moderateScale(12),
    borderRadius: moderateScale(16),
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  estimateIconWrapper: {
    width: moderateScale(38),
    height: moderateScale(38),
    borderRadius: moderateScale(19),
    backgroundColor: '#E8F5E9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.spacing.md,
  },
  estimateDetails: {
    flex: 1,
  },
  estimateTitle: {
    fontSize: theme.typography.sizes.md,
    fontWeight: '800',
    color: theme.colors.textPrimary,
  },
  estimateSubtitle: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.textSecondary,
    marginTop: moderateScale(2),
  },
  // Cart Items List
  itemsContainerCard: {
    backgroundColor: theme.colors.white,
    paddingHorizontal: theme.spacing.lg,
    paddingBottom: theme.spacing.sm,
    marginHorizontal: theme.spacing.md,
    marginBottom: moderateScale(12),
    borderRadius: moderateScale(16),
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  itemsHeaderTitle: {
    fontSize: theme.typography.sizes.sm + 1,
    fontWeight: '800',
    color: theme.colors.textPrimary,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.sm,
    borderBottomWidth: 0.5,
    borderBottomColor: '#F1F5F9',
  },
  itemRow: {
    flexDirection: 'row',
    paddingVertical: theme.spacing.md,
    borderBottomWidth: 1,
    borderColor: '#F8FAFC',
  },
  itemImageWrapper: {
    width: moderateScale(65),
    height: moderateScale(65),
    borderRadius: moderateScale(10),
    backgroundColor: '#F9FAFB',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#F3F4F6',
    marginRight: theme.spacing.md,
  },
  itemImage: {
    width: '85%',
    height: '85%',
  },
  itemMiddle: {
    flex: 1,
    justifyContent: 'space-between',
  },
  itemName: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: '600',
    color: theme.colors.textPrimary,
    lineHeight: rf(18),
  },
  itemWeight: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.textSecondary,
    marginTop: moderateScale(2),
  },
  saveForLaterLink: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.textSecondary,
    textDecorationLine: 'underline',
    marginTop: moderateScale(4),
  },
  itemRight: {
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    width: moderateScale(90),
    height: moderateScale(65),
  },
  itemPrice: {
    fontSize: theme.typography.sizes.sm + 1,
    fontWeight: '800',
    color: theme.colors.textPrimary,
  },
  qtyBadge: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: moderateScale(8),
    paddingVertical: moderateScale(2.5),
    borderRadius: moderateScale(6),
  },
  qtyBadgeText: {
    fontSize: rf(10.5),
    fontWeight: '700',
    color: '#475569',
  },
  // Delivery Instructions Section
  instructionsSection: {
    backgroundColor: theme.colors.white,
    padding: theme.spacing.lg,
    marginBottom: theme.spacing.sm,
  },
  sectionTitle: {
    fontSize: theme.typography.sizes.sm + 1,
    fontWeight: '800',
    color: theme.colors.textPrimary,
    marginBottom: theme.spacing.md,
  },
  instructionsGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  instructionCard: {
    width: '31%',
    backgroundColor: '#F9FAFB',
    borderRadius: theme.borderRadius.sm,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: theme.spacing.sm,
    alignItems: 'flex-start',
    height: moderateScale(90),
    justifyContent: 'space-between',
  },
  instructionCardActive: {
    borderColor: theme.colors.success,
    backgroundColor: '#E8F5E9',
  },
  instructionIconRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  instructionLabel: {
    fontSize: rf(10),
    fontWeight: '700',
    color: theme.colors.textPrimary,
    lineHeight: rf(13),
  },
  // Tipping Card
  tipSectionCard: {
    backgroundColor: theme.colors.white,
    padding: theme.spacing.lg,
    marginBottom: theme.spacing.sm,
  },
  tipRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: theme.spacing.md,
  },
  tipButton: {
    flex: 1,
    height: moderateScale(38),
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: moderateScale(20),
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: moderateScale(3),
    backgroundColor: '#F9FAFB',
  },
  tipButtonActive: {
    borderColor: theme.colors.success,
    backgroundColor: '#E8F5E9',
  },
  tipText: {
    fontSize: theme.typography.sizes.xs + 1,
    fontWeight: '700',
    color: theme.colors.textSecondary,
  },
  tipTextActive: {
    color: theme.colors.success,
  },
  // GSTIN & Summary Cards
  gstinCard: {
    backgroundColor: theme.colors.white,
    padding: theme.spacing.lg,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing.sm,
  },
  gstinLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  gstinText: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: '700',
    color: theme.colors.textPrimary,
    marginLeft: theme.spacing.sm,
  },
  gstinDesc: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.textSecondary,
    marginTop: moderateScale(2),
    marginLeft: theme.spacing.sm,
  },
  // Bill Summary
  billDetailsCard: {
    backgroundColor: theme.colors.white,
    padding: theme.spacing.lg,
    marginHorizontal: theme.spacing.md,
    marginBottom: theme.spacing.xxl,
    borderRadius: moderateScale(16),
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  billRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.sm,
  },
  billLabel: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.textSecondary,
  },
  billValue: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.textPrimary,
    fontWeight: '500',
  },
  billValueFree: {
    color: theme.colors.success,
    fontWeight: '800',
    fontSize: theme.typography.sizes.sm,
  },
  billDivider: {
    height: moderateScale(1),
    backgroundColor: '#F3F4F6',
    marginVertical: theme.spacing.sm,
  },
  billTotalRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  billTotalLabel: {
    fontSize: theme.typography.sizes.md,
    fontWeight: '800',
    color: theme.colors.textPrimary,
  },
  billTotalValue: {
    fontSize: theme.typography.sizes.md + 1,
    fontWeight: '800',
    color: theme.colors.textPrimary,
  },
  // Sticky Bottom Bar
  stickyFooter: {
    position: 'absolute',
    bottom: moderateScale(0),
    left: moderateScale(0),
    right: moderateScale(0),
    backgroundColor: theme.colors.white,
    borderTopLeftRadius: moderateScale(24),
    borderTopRightRadius: moderateScale(24),
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    elevation: 24,
    paddingBottom: theme.spacing.lg,
    zIndex: 999,
  },
  addressSnippetRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#F0FDF4',
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: moderateScale(12),
    borderTopLeftRadius: moderateScale(24),
    borderTopRightRadius: moderateScale(24),
  },
  addressSnippetLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
    marginRight: theme.spacing.md,
  },
  addressSnippetText: {
    fontSize: rf(11),
    color: theme.colors.textPrimary,
    fontWeight: '600',
    marginLeft: moderateScale(6),
    flex: 1,
  },
  checkoutActionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.sm,
  },
  payMethodContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  payMethodLabel: {
    fontSize: rf(10),
    color: theme.colors.textSecondary,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  payMethodValue: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: '800',
    color: theme.colors.textPrimary,
    marginTop: moderateScale(2),
  },
  // Custom Green Place Order Button
  greenPlaceOrderBtn: {
    backgroundColor: theme.colors.success,
    borderRadius: moderateScale(12),
    flexDirection: 'row',
    alignItems: 'center',
    height: moderateScale(48),
    width: moderateScale(200),
    paddingHorizontal: theme.spacing.md,
    justifyContent: 'space-between',
  },
  btnPriceBox: {
    alignItems: 'flex-start',
  },
  btnPriceText: {
    fontSize: theme.typography.sizes.md,
    fontWeight: '900',
    color: theme.colors.white,
  },
  btnPriceLabel: {
    fontSize: rf(8),
    color: 'rgba(255, 255, 255, 0.8)',
    fontWeight: '700',
  },
  btnRightText: {
    fontSize: theme.typography.sizes.sm + 1,
    fontWeight: '800',
    color: theme.colors.white,
  },
  btnDivider: {
    width: moderateScale(1),
    height: moderateScale(24),
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    marginHorizontal: theme.spacing.sm,
  },
  // Address Card
  addressCard: {
    backgroundColor: theme.colors.white,
    padding: theme.spacing.lg,
    marginHorizontal: theme.spacing.md,
    marginBottom: moderateScale(12),
    borderRadius: moderateScale(16),
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  addressIconWrapper: {
    width: moderateScale(32),
    height: moderateScale(32),
    borderRadius: moderateScale(16),
    backgroundColor: '#E8F5E9',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: theme.spacing.md,
    marginTop: moderateScale(2),
  },
  addressCardTitle: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: '800',
    color: theme.colors.textPrimary,
  },
  addressCardName: {
    fontSize: theme.typography.sizes.xs,
    fontWeight: '700',
    color: theme.colors.primary,
    marginTop: moderateScale(2),
  },
  addressCardBody: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.textSecondary,
    marginTop: moderateScale(4),
    lineHeight: rf(16),
  },
  addressEditBtn: {
    paddingVertical: moderateScale(4),
    paddingHorizontal: moderateScale(8),
  },
  addressEditBtnText: {
    color: theme.colors.primary,
    fontSize: theme.typography.sizes.xs + 1,
    fontWeight: '800',
  },
  // Item Badge Capsule
  itemBadgeCapsule: {
    backgroundColor: '#F1F5F9',
    paddingHorizontal: moderateScale(8),
    paddingVertical: moderateScale(3),
    borderRadius: moderateScale(6),
  },
  itemBadgeCapsuleText: {
    fontSize: rf(9.5),
    fontWeight: '700',
    color: '#475569',
  },
  itemRightCentered: {
    justifyContent: 'center',
    alignItems: 'flex-end',
    width: moderateScale(70),
  },
  itemPriceText: {
    fontSize: theme.typography.sizes.sm + 1,
    fontWeight: '800',
    color: theme.colors.textPrimary,
  },
  // Payment Method Card
  paymentMethodCard: {
    backgroundColor: theme.colors.white,
    padding: theme.spacing.lg,
    marginHorizontal: theme.spacing.md,
    marginBottom: moderateScale(12),
    borderRadius: moderateScale(16),
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  paymentCardIconWrapper: {
    width: moderateScale(36),
    height: moderateScale(36),
    borderRadius: moderateScale(8),
    backgroundColor: '#F9FAFB',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
  },
  paymentCardLabel: {
    fontSize: rf(9.5),
    color: theme.colors.textSecondary,
    fontWeight: '600',
  },
  paymentCardValue: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: '800',
    color: theme.colors.textPrimary,
    marginTop: moderateScale(1),
  },
  paymentChangeBtn: {
    paddingVertical: moderateScale(4),
    paddingHorizontal: moderateScale(8),
  },
  paymentChangeBtnText: {
    color: theme.colors.primary,
    fontSize: theme.typography.sizes.xs + 1,
    fontWeight: '800',
  },
  paymentOptionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: moderateScale(12),
    borderBottomWidth: 1,
    borderBottomColor: '#F3F4F6',
  },
  paymentOptionRowActive: {
    backgroundColor: '#F0FDF4',
    marginHorizontal: -theme.spacing.lg,
    paddingHorizontal: theme.spacing.lg,
  },
  optionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  optionIconContainer: {
    width: moderateScale(32),
    height: moderateScale(32),
    borderRadius: moderateScale(6),
    borderWidth: 1,
    borderColor: '#E5E7EB',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: moderateScale(12),
  },
  optionLabel: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: '700',
    color: theme.colors.textPrimary,
  },
  radioCircle: {
    width: moderateScale(20),
    height: moderateScale(20),
    borderRadius: moderateScale(10),
    borderWidth: 2,
    borderColor: '#9CA3AF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioCircleActive: {
    borderColor: theme.colors.primary,
  },
  radioInner: {
    width: moderateScale(10),
    height: moderateScale(10),
    borderRadius: moderateScale(5),
    backgroundColor: theme.colors.primary,
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(255,255,255,0.95)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 9999,
  },
  loadingText: {
    fontSize: rf(16),
    fontWeight: '700',
    color: theme.colors.textPrimary,
    marginTop: theme.spacing.md,
  },
  loadingSubtitle: {
    fontSize: rf(12),
    color: theme.colors.textSecondary,
    marginTop: theme.spacing.xs,
    textAlign: 'center',
    paddingHorizontal: theme.spacing.xl,
  },
  successContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: theme.spacing.xl,
  },
  successTitle: {
    fontSize: rf(20),
    fontWeight: '800',
    color: theme.colors.success,
    marginTop: theme.spacing.md,
  },
  successSubtitle: {
    fontSize: rf(13),
    color: theme.colors.textSecondary,
    marginTop: theme.spacing.xs,
    textAlign: 'center',
  },
});
