import { StyleSheet } from 'react-native';
import { theme } from '../../theme';
import { moderateScale, rf } from '../../utils/responsive';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.white,
  },
  headerAnimWrapper: {
    position: 'absolute',
    top: moderateScale(0),
    left: moderateScale(0),
    right: moderateScale(0),
    zIndex: 100,
  },
  header: {
    paddingHorizontal: theme.spacing.lg,
    paddingTop: moderateScale(22),
    paddingBottom: moderateScale(22),
    alignItems: 'flex-start',
  },
  headerTitle: {
    fontSize: rf(19),
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.white,
  },
  scrollContent: {
    padding: theme.spacing.lg,
    paddingBottom: theme.spacing.xxl,
  },
  orderCard: {
    backgroundColor: theme.colors.white,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: theme.borderRadius.md,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.md,
    ...theme.shadows.sm,
  },
  orderHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderBottomWidth: 0.5,
    borderColor: theme.colors.border,
    paddingBottom: theme.spacing.sm,
    marginBottom: theme.spacing.sm,
  },
  orderIdText: {
    fontSize: theme.typography.sizes.sm,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.textPrimary,
  },
  dateText: {
    fontSize: theme.typography.sizes.xs,
    color: theme.colors.textSecondary,
    marginTop: moderateScale(2),
  },
  statusBadge: {
    paddingHorizontal: moderateScale(8),
    paddingVertical: moderateScale(4),
    borderRadius: theme.borderRadius.sm,
  },
  statusBadgeText: {
    fontSize: rf(9),
    fontWeight: theme.typography.weights.bold,
    textTransform: 'uppercase',
  },
  // Body details
  itemsRow: {
    marginBottom: theme.spacing.sm,
  },
  itemText: {
    fontSize: theme.typography.sizes.xs + 1,
    color: theme.colors.textPrimary,
    lineHeight: rf(18),
  },
  totalAmountText: {
    fontSize: theme.typography.sizes.sm + 1,
    fontWeight: theme.typography.weights.bold,
    color: theme.colors.textPrimary,
    marginTop: theme.spacing.xs,
  },
  // Card Footer Action
  cardDivider: {
    height: moderateScale(1),
    backgroundColor: theme.colors.border,
    marginVertical: theme.spacing.sm,
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  deliveryTimeInfo: {
    fontSize: rf(11),
    color: theme.colors.textSecondary,
  },
  orderAgainBtn: {
    height: moderateScale(32),
    width: moderateScale(100),
  },
  orderAgainText: {
    fontSize: rf(11),
  },
  // Thumbnail Preview Row
  orderItemsPreviewRow: {
    marginVertical: theme.spacing.sm,
    flexDirection: 'row',
  },
  packageIconBg: {
    width: moderateScale(26),
    height: moderateScale(26),
    borderRadius: moderateScale(13),
    backgroundColor: '#DCFCE7',
    justifyContent: 'center',
    alignItems: 'center',
  },
  thumbnailWrapper: {
    width: moderateScale(50),
    height: moderateScale(50),
    borderRadius: moderateScale(8),
    borderWidth: 1.5,
    borderColor: '#F1F5F9',
    backgroundColor: '#FFFFFF',
    marginRight: theme.spacing.sm,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'visible',
  },
  thumbnailImage: {
    width: '85%',
    height: '85%',
    borderRadius: moderateScale(4),
  },
  thumbnailBadge: {
    position: 'absolute',
    bottom: moderateScale(-4),
    right: moderateScale(-4),
    backgroundColor: theme.colors.textSecondary,
    borderRadius: moderateScale(6),
    minWidth: moderateScale(15),
    height: moderateScale(14),
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: moderateScale(3),
  },
  thumbnailBadgeText: {
    color: '#FFFFFF',
    fontSize: rf(8.5),
    fontWeight: 'bold',
  },
  moreItemsCircle: {
    width: moderateScale(40),
    height: moderateScale(40),
    borderRadius: moderateScale(20),
    backgroundColor: '#F1F5F9',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: moderateScale(2),
  },
  moreItemsText: {
    color: theme.colors.textSecondary,
    fontSize: rf(10.5),
    fontWeight: '800',
  },
  orderDetailsLinkBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: moderateScale(4),
  },
  orderDetailsLinkText: {
    color: theme.colors.primary,
    fontWeight: '800',
    fontSize: rf(11.5),
    marginRight: moderateScale(2),
  },
  customOrderAgainBtn: {
    borderRadius: moderateScale(16),
    overflow: 'hidden',
    elevation: 2,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  customOrderAgainBtnGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.md + 4,
    paddingVertical: theme.spacing.xs + 3,
    justifyContent: 'center',
  },
  customOrderAgainBtnText: {
    color: '#FFFFFF',
    fontSize: rf(11),
    fontWeight: 'bold',
  },
  // Empty State
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: theme.spacing.xxl,
    marginTop: moderateScale(80),
  },
  emptyIconWrapper: {
    width: moderateScale(96),
    height: moderateScale(96),
    borderRadius: moderateScale(48),
    backgroundColor: '#FFFFFF',
    elevation: 6,
    shadowColor: '#22C55E',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.12,
    shadowRadius: 12,
    marginBottom: theme.spacing.md,
  },
  emptyIconGradient: {
    width: '100%',
    height: '100%',
    borderRadius: moderateScale(48),
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  sparkleBadge: {
    position: 'absolute',
    top: moderateScale(-2),
    right: moderateScale(-2),
    backgroundColor: '#FFFFFF',
    width: moderateScale(26),
    height: moderateScale(26),
    borderRadius: moderateScale(13),
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#F1F5F9',
    elevation: 3,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  emptyText: {
    fontSize: theme.typography.sizes.lg + 1,
    color: theme.colors.textPrimary,
    fontWeight: '800',
    marginTop: theme.spacing.sm,
    marginBottom: theme.spacing.xs,
  },
  emptySubtext: {
    fontSize: theme.typography.sizes.sm,
    color: theme.colors.textSecondary,
    textAlign: 'center',
    lineHeight: rf(18),
    paddingHorizontal: theme.spacing.md,
    marginBottom: theme.spacing.lg,
  },
  shopNowBtn: {
    marginTop: theme.spacing.xs,
    borderRadius: moderateScale(24),
    overflow: 'hidden',
    elevation: 4,
    shadowColor: theme.colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  shopNowBtnGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: theme.spacing.xxl + 4,
    paddingVertical: theme.spacing.md - 1,
    justifyContent: 'center',
  },
  shopNowBtnText: {
    color: '#FFFFFF',
    fontSize: theme.typography.sizes.sm + 1,
    fontWeight: theme.typography.weights.bold,
  },
});
